### PR TITLE
add custom integration for toyota_na

### PR DESCRIPTION
**Pull request by widewing**
This integration is for interoperate with Toyota (North America) services
https://github.com/widewing/ha-toyota-na

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @widewing, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;wheels-custom-integrations#563).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Review by frenck — CHANGES_REQUESTED** [review]
@widewing 👋 

Have you noticed the CI is failing on this PR? Could you take a look?

**Comment by widewing** [comment]
@frenck yeah i noticed this but not sure how to resolve:
it failed when installing the dependent package `cryptography` but it's a hard requirement for this project. The local install has no issue at all.
The debug message suggests
```
      =============================DEBUG ASSISTANCE=============================
      If you are seeing a compilation error please try the following steps to
      successfully install cryptography:
      1) Upgrade to the latest pip and try again. This will fix errors for most
         users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
      2) Read https://cryptography.io/en/latest/installation/ for specific
         instructions for your platform.
      3) Check our frequently asked questions for more information:
         https://cryptography.io/en/latest/faq/
      4) Ensure you have a recent Rust toolchain installed:
         https://cryptography.io/en/latest/installation/#rust
  
      Python: 3.9.9
      platform: Linux-5.11.0-1022-azure-x86_64-with
      pip: n/a
      setuptools: 60.1.0
      setuptools_rust: 1.1.2
      =============================DEBUG ASSISTANCE=============================
```

**Comment by frenck** [comment]
`cryptography` is already a dependency of Home Assistant.

**Comment by widewing** [comment]
Do you have suggestions how can I correct it?

**Comment by frenck** [comment]
Sorry, I don't have a suggestion for it.

**Pull request closed without merging**
