### PR TITLE
Add Easee EV charger

### PR DESCRIPTION
**Pull request by tmjo**
Add fondbergs Easee EV charger integration to wheel.

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @tmjo, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;wheels-custom-integrations#240).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by frenck** [comment]
If @fondberg aware you are adding this?

**Comment by tmjo** [comment]
yes, he is. I'll ask him to leave a comment here to endorse it.

**Comment by fondberg** [comment]
I'm on board.

**Review by frenck — APPROVED** [review]
Thanks, @tmjo @ @fondberg!

**Pull request merged**
