### PR TITLE
Add o365

### PR DESCRIPTION
**Pull request by RogerSelwyn**
Add o365

### CODE REVIEW

**Review by ludeeus — CHANGES_REQUESTED** [review]
`BeautifulSoup4` and `tzlocal` is used by many other integrations, you should not hard pin those with `==`, use `>=` instead

**Comment by RogerSelwyn** [comment]
> `BeautifulSoup4` and `tzlocal` is used by many other integrations, you should not hard pin those with `==`, use `>=` instead

I can do this for BeautifulSoup4 but a newer version than 2.1 of tzlocal will currently cause the O365 pypi to fail since it has breaking changes in it. Is this a showstopper?

**Comment by ludeeus** [comment]
use `<2.2`

**Comment by RogerSelwyn** [comment]
D

> use `<2.2`

Done

**Review by ludeeus — APPROVED** [review]
Thanks :+1:

**Pull request merged**
