### PR TITLE
Add Tesla custom integration

### PR DESCRIPTION
**Pull request by alandtse**

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
This integration collides with a core integration. Suggestion to change its domain.

Additionally, it relies on packages that are also dependent on in the core. This may cause a breakage when dependencies get out of sync. The suggestion is to depend on those requirements using a range instead of a specific version.

**Comment by alandtse** [comment]
It's meant as a replacement to core. You can't run both at the same time. By forcing an override, it makes it clear. 

For the dependency, are you talking about teslajsonpy or the subdependencies under that?

**Comment by frenck** [comment]
> It's meant as a replacement to core. You can't run both at the same time. By forcing an override, it makes it clear.

It isn't clear, we have the same issue with `shelly` at this moment. It must be changed for this PR to get merged in.

**Comment by alandtse** [comment]
I can change the domain but the custom component won't work with a lower version of `teslajsonpy` like what is in core. Or are you saying a ~0.18.0 is acceptable because the core component will still have to pin?

**Comment by frenck** [comment]
Yeah you could pin in a range like: `teslajsonpy>=0.18.0`

**Review by frenck — APPROVED** [review]
Thanks, @alandtse 👍 

../Frenck 🚂

**Pull request merged**
