### PR TITLE
Add wheels for pfsense integration

### PR DESCRIPTION
**Pull request by raman325**
~~There is currently no dependency but this branch introduces one and will be merged to `main` soon: https://github.com/travisghansen/hass-pfsense/tree/device_tracker~~

The dependency is now in main

### CODE REVIEW

**Comment by raman325** [comment]
guess I can only open this once we've merged to main

**Review by frenck — CHANGES_REQUESTED** [review]
This integration hard pins a generic dependency:

```json
  "requirements": ["mac-vendor-lookup==0.1.11"],
```

This dependency is also used by built-in Home Assistant integration, therefore it is preferred to ping these to a range instead.

**Comment by raman325** [comment]
how would you recommend we use a range? Set a min but no max? Or should we have a max too?

**Comment by frenck** [comment]
> how would you recommend we use a range? Set a min but no max? Or should we have a max too?

I don't think you can set a max at this point

**Comment by raman325** [comment]
this has been fixed upstream @frenck

**Comment by travisghansen** [comment]
Thanks to both of you for helping get this over the hill!

**Review by frenck — APPROVED** [review]
Thanks! 👍

**Pull request merged**
