### PR TITLE
Add metlink

### PR DESCRIPTION
**Pull request by make-all**
These are two custom components maintained by me, which have dependencies on third-party libraries.

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @make-all, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;wheels-custom-integrations#415).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Review by frenck — CHANGES_REQUESTED** [review]
Please don't add multiple things in a single PR.

**Comment by make-all** [comment]
OK, I have removed tuya-local for now.

**Review by frenck — APPROVED** [review]
Thanks, @make-all 👍

**Pull request merged**
