### PR TITLE
HausMon monitor integration

### PR DESCRIPTION
**Pull request by liber-tas**
Adding a new integration for HausMon (see https://hausnet.io)

### CODE REVIEW

**Comment by pvizeli** [comment]
Pin the version

**Review by frenck — CHANGES_REQUESTED** [review]
As requested by Pascal above, requirements need to be pinned to a specific version. 

Please adjust your upstream manifest file.

**Comment by liber-tas** [comment]
Done. Let me know if there's anything else. Thanks!

**Comment by ludeeus** [comment]
@liber-tas Can you rebase this, most of the CI has changed since this was opened. Thanks :+1:

**Comment by ludeeus** [comment]
Closing this as it has gone stale, feel free to open a new PR when you are ready :+1:

**Pull request closed without merging**
