### PR TITLE
added ytube_music_player

### PR DESCRIPTION
**Pull request by KoljaWindeler**
added wheel file for ytube_music_player

### CODE REVIEW

**Comment by KoljaWindeler** [comment]
hey @frenck could you have a look, this is blocking the HACS pull request https://github.com/hacs/default/pull/733
Thanks Kolja

**Comment by frenck** [comment]
@KoljaWindeler In general, please don't ping people. Just await patiently, we have 600 PRs open in the Home Assistant organization. Thanks 👍

**Comment by KoljaWindeler** [comment]
Hi there, I read, understood and respected your message.

But I'm wondering if there is anything wrong with the pull request, quite a few other pull requests have been merged in the meantime. We're not talking about a complex logic here, its just the wheel meta-package. I'd consider it as nobrainer. 

Is this some kind of retaliation for pushing it after the first two weeks?

Let me know if there is an issue with the request
Marry x-mas, Kolja

**Review by frenck — CHANGES_REQUESTED** [review]
We are enjoying a holiday right now. I do merge/check some from time to time, which isn't fifo, but merely stuff I randomly do during my time off.


image


The manifest file isn't found and returns a 404.

**Comment by KoljaWindeler** [comment]
Thanks for your dedication and hard work.
I'm trying to support with this integration, at least a little..

**Review by frenck — CHANGES_REQUESTED** [review]
The following requirements do not have pinning:

```
"pytube",
"integrationhelper"
```

It is strongly advised to pin those, or else you won't be able to handle/control upgrades on those dependencies.

**Comment by KoljaWindeler** [comment]
done

**Review by frenck — APPROVED** [review]
Thanks! 👍 

Happy Holidays!

**Comment by KoljaWindeler** [comment]
Happy Holidays!

**Pull request merged**
