### PR TITLE
Add Meural Canvas integration

### PR DESCRIPTION
**Pull request by GuySie**

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @GuySie, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;wheels-custom-integrations#82).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by frenck** [comment]
Hi there @GuySie!

Looking at the integration, it does not have any requirements:

`"requirements": [],`

This means there is no wheel for us to build 😉 

Adding this custom integration to this repository would have no effect, so going to close this PR.

Nevertheless, thanks for contributing 👍

**Comment by GuySie** [comment]
Apologies @frenck, I saw this on the checklist for adding icons to home-assistant/brands for a custom component so thought it was always required.

**Comment by frenck** [comment]
Aaah right! No, it is merely a suggestion/reminder for the reviewer there is another related PR open and a suggestion/reminder for the contributor it can be added here as well.

**Pull request closed without merging**
