### PR TITLE
add fantasy premier league integration

### PR DESCRIPTION
**Pull request by Hojland**

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @Hojland, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;wheels-custom-integrations#503).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Review by ludeeus — CHANGES_REQUESTED** [review]
`pytz` is used in the core, please loosen the pinning of that.

**Comment by Hojland** [comment]
I loosened up the pytz requirement, and changed the other to minimum requirements. Thank you!

**Review by ludeeus — APPROVED** [review]
Thanks :+1:

**Pull request merged**
