### PR TITLE
add dwains_dashboard.json

### PR DESCRIPTION
**Pull request by dwainscheeren**
Add dwains dashboard to wheels

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @dwainscheeren, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;wheels-custom-integrations#364).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Review by frenck — CHANGES_REQUESTED** [review]
According to the manifest:

```
"requirements": ["jinja2"],
```

However, Jinja2 is a core requirement and that should thus not be in the manifest.
See:

https://developers.home-assistant.io/docs/creating_integration_manifest#custom-integration-requirements

**Comment by dwainscheeren** [comment]
Removed it, please recheck @frenck

**Comment by frenck** [comment]
As there are now no requirements left, it means there are no wheels for us to build 👍

**Pull request closed without merging**
