### PR TITLE
Create person_location.json

### PR DESCRIPTION
**Pull request by rodpayne**

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
Hi there @rodpayne!

Thanks for the PR, but could you place make sure the build passes? Thanks! 👍

**Comment by rodpayne** [comment]
@frenck
I updated manifest.json in my repository.  How do I rerun  the test?

**Comment by frenck** [comment]
I've re-triggered them.

**Comment by rodpayne** [comment]
@frenck
I added requirements to manifest.json in my repository.  Could you please retrigger the test?

**Comment by frenck** [comment]
```json
  "requirements": [
    "aiohttp>=3.7.3",
    "integrationhelper>=0.2.2",
    "voluptuous==0.12.1"
  ],
```

From the manifest, both aiohttp & voluptuous, are core requirements of Home Assistant, I personally would not add them. Pinning to a minimal version (like aiohttp), is OK if really needed, however the exact pin on voluptuous, is not OK. That will cause issues if Home Assistant is upgrading.

**Comment by rodpayne** [comment]
So it sounds like I do not actually need this to be added to wheels-custom-integration because all three requirements are already in Home Assistant and the installed versions are fine.   The HACS validation led me to believe that I needed the PR, but that was only because I had added requirements based on messages that came up in linting.

If not needed, I will close the PR.

**Comment by frenck** [comment]
`integrationhelper` is not part of Home Assistant?

**Comment by ludeeus** [comment]
wow... that's still in use :/, please don't use it (I started that thing, but it was never finished)

**Comment by rodpayne** [comment]
@ludeeus I am a novice at creating integrations, but I have seen this code in examples often enough that I thought it was a standard.  Now I know better.  (Just like I thought that I needed to add to wheels-custom-integrations.)

```
from integrationhelper.const import CC_STARTUP_VERSION

        # log startup message:
        _LOGGER.info(
            CC_STARTUP_VERSION.format(
                name=DOMAIN, version=VERSION, issue_link=ISSUE_URL
            )
        )
```
Thanks.

**Pull request closed without merging**
