### PR TITLE
Create deltasol.json

### PR DESCRIPTION
**Pull request by dm82m**

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
Your integration has `requests` in its requirements, however, this is a default dependency of Home Assistant:

See: <https://github.com/home-assistant/core/blob/dev/requirements.txt#L20>

So you don't need to add that requirement.

**Comment by dm82m** [comment]
thanks for your feedback, I removed the requirement

**Comment by dm82m** [comment]
@frenck anything else needed here?

**Review by frenck — APPROVED** [review]
Thanks, @dm82m 👍 
Looks good now!

**Pull request merged**
