### PR TITLE
Create localtuya.json

### PR DESCRIPTION
**Pull request by rospogrigio**

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @rospogrigio, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;wheels-custom-integrations#161).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by KTibow** [comment]
@rospogrigio can you do an empty commit and force push?

**Comment by frenck** [comment]
There is no need to put cryptography in the requirements, as it is a base/core dependency already.
You should remove that requirement from your custom component to prevent issues in the future.

**Comment by rospogrigio** [comment]
> There is no need to put cryptography in the requirements, as it is a base/core dependency already.
> You should remove that requirement from your custom component to prevent issues in the future.

OK I have just done it.

**Comment by frenck** [comment]
Thanks, @rospogrigio, that leave your custom integration with no third-party packages to depend on. Is this correct?

If so, you can close this PR, as there is nothing for us to build wheels for in that case.

**Comment by rospogrigio** [comment]
Yes, that is correct. 
I am having a doubt you can probably help me with: one check in this PR request is failing:
https://github.com/hacs/default/pull/662
Because it could not find the manifest.json file. 
So I moved it from custom_components/localtuya to the root of my repo but now the check in this PR is failing. Where should the manifest.json be correctly placed? Or should I have 2 copies in different folders?
Thank you

**Comment by KTibow** [comment]
https://dev.azure.com/home-assistant/Core/_build/results?buildId=57029&view=logs&j=5474ba80-d37c-5f5f-2aea-f2830af4b9d6&t=4864bab3-4a04-5955-f9e5-80d721dfcb1d&l=201
> The integration in components/localtuya.json, does not seem to have any Python requirements.
Adding it to this repository has no use, since there are nothing to build for it.

Please close.

**Comment by rospogrigio** [comment]
OK, thank you

**Pull request closed without merging**
