### PR TITLE
RRD Recorder

### PR DESCRIPTION
**Pull request by dgomes**
Requesting the addition of RRD Recorder Custom Integration

### CODE REVIEW

**Comment by dgomes** [comment]
This integration requires a python package which has a dependency on a C library (librrdtool)

**Comment by dgomes** [comment]
Is there any way of declaring the dependency of a upstream C library for the upstream python requirement ?

**Comment by frenck** [comment]
@dgomes There currently is not.

**Comment by dgomes** [comment]
Thank you @frenck which repository has the build script ?

But this also means the test will always fail :(

**Comment by frenck** [comment]
Well, by the look of the build output, it seems that it is missing `rrdtool-dev`. The added `librrd` does not supply the development headers.

**Pull request closed without merging**
