### PR TITLE
Adding ble_monitor.json

### PR DESCRIPTION
**Pull request by Ernst79**
Adding ble_monitor to the Python Wheels repository

### CODE REVIEW

**Comment by Ernst79** [comment]
Sorry, I have no idea why the checks fail. Can you help me out?

**Comment by frenck** [comment]
image

You need to use the URL to the raw file, not the GitHub page.

**Comment by Ernst79** [comment]
Thanks, I was focussed on the line7, column 10

**Review by frenck — APPROVED** [review]
Thanks! 👍

**Pull request merged**
