### PR TITLE
Added rki_covid

### PR DESCRIPTION
**Pull request by thebino**

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @thebino, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;wheels-custom-integrations#205).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Review by frenck — CHANGES_REQUESTED** [review]
You should not pin `aiohttp` like that. `aiohttp` is a core dependency of Home Assistant, it will always be there. Forcing it by pinning will cause issues with people using your custom component.

**Comment by thebino** [comment]
Thanks for the feedback @frenck.
So you recommend to remove aiohttp as dependency in the manifest?

**Comment by frenck** [comment]
Yes, for a Home Assistant component, that dependency will always be there.

**Comment by thebino** [comment]
I just removed it from the manifest.

**Review by thebino — COMMENTED** [review]
aiohttp dependency removed

**Comment by frenck** [comment]
Thanks @thebino! 👍 

That also means, your custom component has no requirements/dependencies. So, there are no wheels to build 😄 

Therefore, adding the manifest to this repository has no effect (which is nice, as your custom component will just install in a flash).

**Comment by thebino** [comment]
Ah, thats the crux behind it. Thanks a lot for the explanation.

**Pull request closed without merging**
