### PR TITLE
Added TV4 Play integration

### PR DESCRIPTION
**Pull request by lindell**

### CODE REVIEW

**Comment by frenck** [comment]
The integration has `requests` as a requirement in its manifest, however, that should not be listed there.

See: <https://developers.home-assistant.io/docs/creating_integration_manifest/#custom-integration-requirements>

**Review by frenck — CHANGES_REQUESTED** [review]
Setting correct review status

**Comment by frenck** [comment]
That means that this integration has no requirements:

```
    "requirements": []
```

and thus no Python wheels for us to build and therefore I can close this PR.

**Comment by lindell** [comment]
Thanks for the responses 👍 

I think it might be good to describe what this repository does in the readme. For a native Python developer it is probably obvious, but many customer component developers are simply programmers of other languages trying to solve something in HA 😄 After reading up on Python wheels, it is much clearer to me. But it took some time to even find it, since I had no idea what "wheels" were referring to.

I googled things such as "wheels home assistant" at first, but it does not give any indication of what wheels are.

This will probably decrease the number of unnecessary requests coming from the brands repo indicating that you should add it here.
image

**Comment by frenck** [comment]
> This will probably decrease the number of unnecessary requests coming from the brands repo indicating that you should add it here.

Its fine! We've found something on the integration during the process as well, so things improve 🎉

**Pull request closed without merging**
