### PR TITLE
add astroweather integration

### PR DESCRIPTION
**Pull request by mawinkler**

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
@mawinkler Please make sure the build passes. Thanks! 👍

**Comment by mawinkler** [comment]
> @mawinkler Please make sure the build passes. Thanks! 👍

@frenck I will, but honestly I'm trying to figure out how... any hints?
"Package asyncio is not compatible with Python 3.8 standard library"

**Comment by ludeeus** [comment]
one of the requirements you have listed in your manifest file installs `asyncio` that is a standard module in Python and this causes conflicts, `asyncio` should be removed as a dependency of that package.

**Comment by mawinkler** [comment]
> one of the requirements you have listed in your manifest file installs `asyncio` that is a standard module in Python and this causes conflicts, `asyncio` should be removed as a dependency of that package.

Thanks @ludeeus and it makes total sense. Manifest is updated.

**Comment by ludeeus** [comment]
no? 
`pyastroweatherio` still install `asyncio` <https://github.com/mawinkler/pyastroweatherio/blob/main/setup.py#L17>

**Comment by mawinkler** [comment]
> no?
> `pyastroweatherio` still install `asyncio` https://github.com/mawinkler/pyastroweatherio/blob/main/setup.py#L17

long day, forgot the push

**Comment by ludeeus** [comment]
<https://github.com/mawinkler/astroweather/blob/main/custom_components/astroweather/manifest.json#L13> Still needs to be bumped to the version that no longer installs `asyncio`

**Comment by mawinkler** [comment]
> https://github.com/mawinkler/astroweather/blob/main/custom_components/astroweather/manifest.json#L13 Still needs to be bumped to the version that no longer installs `asyncio`

done

**Review by frenck — APPROVED** [review]
Thanks, @mawinkler 👍

**Pull request merged**
