### PR TITLE
Add FitX custom component

### PR DESCRIPTION
**Pull request by Raukze**
Add FitX Gym Usage custom component

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @Raukze, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;wheels-custom-integrations#546).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Review by frenck — CHANGES_REQUESTED** [review]
Looking upstream:

```
"requirements": ["beautifulsoup4==4.9.3", "requests==2.26.0"],
```

`requests` is already a requirement of Home Assistant Core, and should therefore not be included in the manifest.

Additionally, `beautifulsoup4` is used by more integrations and a more common dependency. It is recommended to pin such requirements with a range.

**Comment by Raukze** [comment]
Thanks for the feedback!

Updated the requirements. Removed `requests` and pinned `beautifulsoup4>=4.4.0`.

**Review by frenck — APPROVED** [review]
Thanks, @Raukze 👍

**Pull request merged**
