### PR TITLE
feat: add ha hatch custom integration

### PR DESCRIPTION
**Pull request by dahlb**

### CODE REVIEW

**Comment by frenck** [comment]
Note to self: needs `awscrt` musl wheels.

**Comment by niemyjski** [comment]
+1

**Comment by niemyjski** [comment]
@frenck any chance we can get this merged?

**Review by niemyjski — APPROVED** [review]

**Comment by tpansino** [comment]
@dahlb, could you update this PR? It looks like the maintainers here have change how the repo is implemented since you opened it.

From the GitHub Actions code in here, it looks like they're just building wheels for each dependency in the `requirements.txt` file now, so you probably just need to change this PR to add a line for `awscrt`.

**Comment by dahlb** [comment]
@tpansino thanks for the walkthrough. Sorry I didn't keep up with the repo changes. I opened a new PR with your suggested fix.

**Pull request closed without merging**
