### PR TITLE
Create gecko.json

### PR DESCRIPTION
**Pull request by gazoodle**

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @gazoodle, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;wheels-custom-integrations#209).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Review by frenck — CHANGES_REQUESTED** [review]
You might want to pin the version of the `gecko` package version to use, in your manifest.

**Comment by gazoodle** [comment]
> You might want to pin the version of the `gecko` package version to use, in your manifest.

I now have "geckolib>=0.3.16" in the manifest

**Review by frenck — APPROVED** [review]
That is already better, however, I won't automatically update on the user-end when you release a new geckolib. In general, we recommend pinning a specific version on integration level (for direct dependencies like custom packages).

Nevertheless; Thanks for adjusting 👍 

Happy Holiday 🎄

**Comment by gazoodle** [comment]
> That is already better, however, I won't automatically update on the user-end when you release a new geckolib. In general, we recommend pinning a specific version on integration level (for direct dependencies like custom packages).
> 
> Nevertheless; Thanks for adjusting 👍
> 
> Happy Holiday 🎄

I’m not sure I fully understand. If I update geckolib with new functionality and release it, then consume that in the integration updating the requirement as appropriate, are you saying that it won’t automatically update?

Should I be pinning a specific version of geckolib to a specific release of the integration?

Thanks, and happy holidays to you too. Stay safe.

**Pull request merged**
