### PR TITLE
add wort_des_tages

### PR DESCRIPTION
**Pull request by Ludy87**

### CODE REVIEW

**Review by ludeeus — CHANGES_REQUESTED** [review]
`beautifulsoup4` is also used by a core integration, please loosen the pinning with `>=`  instead of `==`

**Comment by Ludy87** [comment]
> `beautifulsoup4` is also used by a core integration, please loosen the pinning with `>=` instead of `==`

fyi

**Comment by Ludy87** [comment]
@ludeeus https://raw.githubusercontent.com/Ludy87/astra_germany_wort_des_tages/main/custom_components/wort_des_tages/manifest.json

**Review by ludeeus — APPROVED** [review]
Thanks :+1:

**Pull request merged**
