### PR TITLE
Add support for nws_alerts custom integration

### PR DESCRIPTION
**Pull request by finity69x2**

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @finity69x2, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;wheels-custom-integrations#79).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by finity69x2** [comment]
I think I've fixed the error.

How do the checks get re-run?

**Comment by ludeeus** [comment]
You do not have any requirements for building wheels, so adding it here would not do anything :)

```json
"requirements": []
```

**Comment by finity69x2** [comment]
Ok, I was trying to add a PR for the icons and it said I needed to submit a PR here first as one of the checks.

I didn't realize it was a "if required..." option.

**Pull request closed without merging**
