### PR TITLE
Adding glocaltokens.json

### PR DESCRIPTION
**Pull request by leikoilja**

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
The given manifest file does not exists?

**Comment by leikoilja** [comment]
Uh, rookie mistake, sorry, @frenck. 
Opened this PR and then decided to rename the `custom_component` for better consistency and forgot to update it here.

**Comment by leikoilja** [comment]
@frenck, now that the failing `jq` dependency is removed is there a way to re-trigger the tests?

**Comment by DurgNomis-drol** [comment]
Hey 
Im helping @leikoilja with ha-glocaltokens. In my research to find what have to be done to make it possible to build wheels for grpcio and grpcio-tools succesfully on Arm/Alpine. I just went into bash in my docker installation and add `apk add gcc g++ linux-headers` and it then it build when i run pip install grpcio grpcio-tools afterwards. 

I dont know much about building wheels or how this works in general. Soo please correct me if im wrong in this.

**Comment by leikoilja** [comment]
I have found that HA might have issues with wheel building for newest grpci versions and is currently pinned to a specific version `grpcio==1.31.0`. I have just tried doing the same for `glocaltokens` package and the package has worked well. Will see if the tests will pass now :)

**Comment by leikoilja** [comment]
Okay, I ll just close this PR for now, since we still need to find a way around `grpcio` and clean up the repo a bit. Will create a new PR when it's ready.

**Pull request closed without merging**
