### PR TITLE
add ocpp.json

### PR DESCRIPTION
**Pull request by lbbrhzn**

### CODE REVIEW

**Comment by lbbrhzn** [comment]
hurray!

**Review by frenck — CHANGES_REQUESTED** [review]
This package uses `websockets` as a package upstream.

In general, it is strongly discouraged to pin generic/common packages this hard from a package. As it is guaranteed to cause conflicts with other packages that have different requirements.

Does your integration specifically require that specific pinned version?

**Comment by lbbrhzn** [comment]
No, I'll update to >= x.y Not sure what x and y should be though

**Review by frenck — APPROVED** [review]

**Pull request merged**
