### PR TITLE
add Luxtronik integration

### PR DESCRIPTION
**Pull request by Bouni**

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
It is recommended to pin direct dependencies like libraries that communicate directly.

```
  "requirements": [
    "luxtronik"
  ],
```

Or else you can end up having functional mismatches between the custom integration and the client library.

**Comment by Bouni** [comment]
Done!

Is there actually a sane way of retrigger the CI checks? Adding or deleting whitespaces feels messy :confused:

**Comment by frenck** [comment]
We can re-trigger that for you, alternatively, you can also just push an empty commit (no need to change contents).

`git commit --allow-empty -m "Empty commit to re-trigger CI"`

**Comment by Bouni** [comment]
Thanks for this hint @frenck :blush:

**Review by frenck — APPROVED** [review]
Thanks, @Bouni 👍

**Pull request merged**
