### PR TITLE
Create openhab.json

### PR DESCRIPTION
**Pull request by kubawolanin**

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
You might want to pin the integration specific dependency here?

```
  "requirements": [
    "python-openhab"
  ],
```

What if you make a breaking change in the openhab package now?

**Comment by kubawolanin** [comment]
> You might want to pin the integration specific dependency here?
> 
> ```
>   "requirements": [
>     "python-openhab"
>   ],
> ```
> 
> What if you make a breaking change in the openhab package now?

Good point, I'll have it fixed with my next push

**Comment by kubawolanin** [comment]
@frenck fixed as advised:
https://github.com/kubawolanin/ha-openhab/blob/master/custom_components/openhab/manifest.json#L8

Cheers

**Review by frenck — APPROVED** [review]
Thanks, @kubawolanin 👍

**Pull request merged**
