### PR TITLE
Add aiogithubapi

### PR DESCRIPTION
**Pull request by ludeeus**
Used by HACS <https://github.com/hacs/integration/blob/main/custom_components/hacs/manifest.json#L23>

### CODE REVIEW

**Comment by frenck** [comment]
This requires already publishes wheels:

CleanShot 2024-09-13 at 09 18 09@2x

Any reason why we need to include it here at this point?

../Frenck

**Comment by ludeeus** [comment]
uv with extra index url requires the wheel to exist on the specified server

**Comment by frenck** [comment]
Hmmm that almost sounds like an issue with `uv`, as it almost looks like it behaves as if you set `UV_INDEX_URL` (while you did set `UV_EXTRA_INDEX_URL`). It should honor the existing index when setting an extra index.

**Comment by ludeeus** [comment]
If the package does not exist, it will happily reach out to pypi.
But if the requested version of that package does not exist, it does not.
Unless you override the behavior with an unsafe option.

https://docs.astral.sh/uv/reference/settings/#index-strategy

**Review by frenck — APPROVED** [review]

**Comment by ludeeus** [comment]
Thanks!

**Pull request merged**
