### PR TITLE
feat: add scikit-learn

### PR DESCRIPTION
**Pull request by Lash-L**
For a custom component i'm working on/ thinking about releasing, I need scikit-learn to be wheeled for alpine. 

This is an issue others have had in the past: https://community.home-assistant.io/t/how-to-use-scikit-learn-with-a-custom-intigration/536939

https://github.com/home-assistant/operating-system/issues/3040

scikit-learn has decided as of a few months ago the do not plan to release a musllinux wheel https://github.com/scikit-learn/scikit-learn/issues/27004#issuecomment-1966926217

I can rebuild the model I want to use from scratch, but I would prefer to just be able to use a robust and optimized model like what scikit-learn has. I am trying to use a decision tree inducer and seemingly most other packages out there either a) aren't as good as scikit-learn by a lot or b) use scikit-learn under the hood. If this isn't ideal for any reason, that's okay, just let me know.

Thanks!

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
Hi there @Lash-L 👋 

The CI doens't pass. Can you take a look?

Thanks! 👍 

../Frenck

**Comment by Lash-L** [comment]
Seems as if it wants a Fortran compiler too

../meson.build:78:0: ERROR: Unknown compiler(s): [['gfortran'], ['flang'], ['nvfortran'], ['pgfortran'], ['ifort'], ['ifx'], ['g95']]

I suppose I need to figure out what Fortran compiler is best across different archs and add it - would that go here?

https://github.com/home-assistant/wheels-custom-integrations/blob/fc6c89aa8b20761f012bcacf5e915e7112a99f6c/.github/workflows/wheels.yml#L91

Is that something fine to do?

**Comment by frenck** [comment]
Sure, extra build dependencies can be added if needed 👍

**Comment by Lash-L** [comment]
We can see if that does the trick

**Comment by frenck** [comment]
CI failing. Please wait with marking a PR ready for review, until the CI passes.

../Frenck

**Comment by Lash-L** [comment]
Sorry about that, I couldn't tell if the checks would pass as I haven't committed to this repo before so I marked it as ready in a sense of ready for the ci to run. Will run ci locally on my branch until I figure it out 👍🏻

**Comment by Lash-L** [comment]
Apparently cannot run the ci on a local branch, but I will test with a docker container running alpine later 👍

**Comment by Lash-L** [comment]
Okay - it seems to work locally for me, I think it is ready for a ci run here!

**Comment by frenck** [comment]
Seems like i386/amd64 will pass now, the ARM-based ones do fail at this point.

**Comment by Lash-L** [comment]
Odd - I am able to install xsimd and openblas on my rpi running HA and Alpine. I'll have to experiment some more and try to figure it out

**Comment by xkns** [comment]
I'm also very interested in this and am happy to help. If there is anything I can do please let me know.

**Comment by Lash-L** [comment]
I'm out of the country rn but will continue trying to figure this out when I get back

**Comment by Lash-L** [comment]
Running docker commands directly and it succeeds on amd64, running another but it is going slow and i'm going to bed, but i figured i'd push the update and if you had a chance, a ci run will tell us for sure if it is working or not. If you don't have a chance, I'll try again on some other types, next time i have some free time

**Comment by Lash-L** [comment]
Successful on a second arch, so this is ready for a CI run

**Comment by Lash-L** [comment]
I'm going to close this as I believe it is not a feasible task unfortunately. scikit-learn depends on scipy and scipy's installation takes a very long time on some of the alpine archs (aarch64, armhf, armv7) Scipy provides musllinux wheels for x86-64  (https://pypi.org/project/scipy/#files). But when wheels are not provided - it can take up to 5/6 hours to install, which is not feasible: https://github.com/Lash-L/wheels-custom-integrations/actions/runs/9735326489

Perhaps someone else can look into this in the future, I'd be happy to share what I know

**Comment by xkns** [comment]
It's never easy, is it?

Anyways, thanks for giving it a shot.

Guess one could package the necessary sklearn source files manually with one's custom component, as long as there is no redistribution.

**Pull request closed without merging**
