### PR TITLE
worldtidesinfocustom

### PR DESCRIPTION
**Pull request by jugla**
add worldtidesinfo custom

### CODE REVIEW

**Comment by jugla** [comment]
I've signed the CLA with URL
[https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant/wheels-custom-integrations#423](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant/wheels-custom-integrations#423)

**Comment by jugla** [comment]
oups (I used also this link [https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant/wheels-custom-integrations#422](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant/wheels-custom-integrations#422)
sorry

**Review by frenck — APPROVED** [review]
Thanks, @jugla 👍

**Comment by jugla** [comment]
Thanks !

**Comment by frenck** [comment]
Your welcome, @jugla 👍

**Pull request merged**
