### PR TITLE
add signalmessenger integration

### PR DESCRIPTION
**Pull request by MichaelBitard**
I want to add this integration to hacs, it appears this is required since my integration uses python.

Related to https://github.com/agileek/hassio-addons/pull/29

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
👋  @MichaelBitard, the build is failing, could you please take a look?

**Comment by MichaelBitard** [comment]
@frenck I fixed the next issue, can you relaunch the checks? I don't have the rights to do that

**Comment by ludeeus** [comment]
`requests` is a core requirement <https://github.com/home-assistant/core/blob/dev/requirements.txt#L20> and you should remove that from your manifest file, when that is removed there are no requirements to build wheels for in your manifest so I'm closing this PR 👍

**Comment by MichaelBitard** [comment]
I did not knew that!

Thanks!

**Pull request closed without merging**
