### PR TITLE
Added openmediavault integration

### PR DESCRIPTION
**Pull request by tomaae**

### CODE REVIEW

**Comment by tomaae** [comment]
Yes, integration have no requirements. It works fine on new HA installation.

**Comment by ludeeus** [comment]
Then there are no reason to add it to this repository since there would be nothing to build.
Thanks anyway 👍

**Comment by tomaae** [comment]
> 
> 
> Then there are no reason to add it to this repository since there would be nothing to build.
> Thanks anyway 👍

isnt it required for brands icons?

**Comment by ludeeus** [comment]
No, only if you have requirements, if someone raises a question about it, just link to this PR and it will be good 👍

**Pull request closed without merging**
