### PR TITLE
Add egauge component

### PR DESCRIPTION
**Pull request by neggert**

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @neggert, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;wheels-custom-integrations#332).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Review by frenck — CHANGES_REQUESTED** [review]
```
  "requirements": ["egauge-async"]
```

You might want to consider pinning that requirement to prevent surprises in the future. E.g., if you need to make a breaking change in `egauge-async` and adjust the custom integration for it.

**Comment by neggert** [comment]
@frenck Done!

**Review by frenck — APPROVED** [review]
Thanks, @neggert 👍

**Pull request merged**
