### PR TITLE
Create peaqev.json

### PR DESCRIPTION
**Pull request by elden1337**

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @elden1337, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;wheels-custom-integrations#616).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Review by frenck — CHANGES_REQUESTED** [review]
```
    "requirements": [
      "homeassistant>=2022.4.5",
      "peaqevcore>=0.0.21"
    ],
```

`homeassistant` should not be part of an integration requirement.

Please note: We are currently no processing custom wheels; as we are awaiting a refactor of this repository.

**Comment by elden1337** [comment]
Thanks. manifest.json has been updated. Reason for the req added was the re-write of sensors in 2022.4.5.

**Comment by frenck** [comment]
>  Reason for the req added was the re-write of sensors in 2022.4.5.

It are python requirements that are installed... so it will install itself in such cases (which is really not something you'd want to trigger... 😬 )

**Comment by elden1337** [comment]
you live you learn... thanks for input

**Comment by frenck** [comment]
Home Assistant will move to Python 3.10 this release (2022.7), including support for PEP-656 with musl wheels.

For this PR, there are no additional requirements we need to build, as they are universal wheels that do not require any specific musl distribution and are just fetched from PyPi or already present on our wheels service.

In conclusion, we no longer need to add/merge this PR for those reasons. Making everything a tiny bit easier to maintain and less complex for the future 👍 

If you have any questions, feel free to reach out.

../Frenck

**Pull request closed without merging**
