### PR TITLE
add SmartRent custom integration

### PR DESCRIPTION
**Pull request by ZacheryThomas**
Add custom integration wheels for my [SmartRent](https://github.com/ZacheryThomas/homeassistant-smartrent) project

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @ZacheryThomas, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;wheels-custom-integrations#568).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by homeassistant** [comment]
Hi @ZacheryThomas, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;wheels-custom-integrations#568).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by homeassistant** [comment]
Hi @ZacheryThomas, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;wheels-custom-integrations#568).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Review by frenck — CHANGES_REQUESTED** [review]
@ZacheryThomas, The build doens't pass, can you please take a look?

**Review by frenck — APPROVED** [review]
Thanks, @ZacheryThomas 👍

**Pull request merged**
