### PR TITLE
Create vivint.json

### PR DESCRIPTION
**Pull request by natekspencer**

### CODE REVIEW

**Comment by frenck** [comment]
Thanks for the PR @natekspencer!

image

However, packages need to be uploaded to PyPi in order for the builds to pass.

**Review by frenck — CHANGES_REQUESTED** [review]
Please upload to PyPi

**Comment by natekspencer** [comment]
@frenck this has been fixed

**Review by natekspencer — COMMENTED** [review]
What do I need to do to rerun the actions?

**Review by frenck — APPROVED** [review]
Thanks, @natekspencer 👍

**Pull request merged**
