### PR TITLE
Add simple icons custom integration

### PR DESCRIPTION
**Pull request by vigonotion**

### CODE REVIEW

**Comment by pvizeli** [comment]
You don't have any requirements?

**Comment by vigonotion** [comment]
Let me check, that might be a mistake

**Comment by vigonotion** [comment]
The code only requires aiohttp, but I've never seen someone adding that to the dependencies. But I will add it if it's considered a real dependendy

**Comment by frenck** [comment]
aiohttp is already a dependency of the Home Assistant core itself. There is no need to add it in that case.

**Comment by vigonotion** [comment]
I guess I can close this PR then, as it would not add any value when there are no dependencies

**Pull request closed without merging**
