### PR TITLE
Update manifest in accordance to changes in teufel_raumfeld repository

### PR DESCRIPTION
**Pull request by B5r1oJ0A9G**
Update manifest in accordance to changes in teufel_raumfeld repository to comply with https://hacs.xyz/docs/publish/integration.

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @drprofesq, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;wheels-custom-integrations#259).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Review by frenck — CHANGES_REQUESTED** [review]
There are unrelated commits in this PR, please git rebase your branch onto the upstream master

**Comment by homeassistant** [comment]
Hi @drprofesq, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;wheels-custom-integrations#259).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by B5r1oJ0A9G** [comment]
I was not able to manage the rebase, git is not my hobby horse. Therefore I decided to go from scratch with a new fork / pull request (coming soon).

**Pull request closed without merging**
