### PR TITLE
Add dobiss.json

### PR DESCRIPTION
**Pull request by kesteraernoudt**
adding custom integration for dobiss

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @kesteraernoudt, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;wheels-custom-integrations#222).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by kesteraernoudt** [comment]
I've updated the project and dependencies which now pass these tests locally. Not sure how to trigger a re-check...

**Review by frenck — APPROVED** [review]
Thanks, @kesteraernoudt 👍 

Happy New Year 🥂

**Review by frenck — CHANGES_REQUESTED** [review]
Oh, just realized the build error (still on my morning ☕ )


image

Re-triggered the build

**Review by frenck — APPROVED** [review]
Alright passed! Let's try this again 🙈 

Happy New Year 🥂

**Comment by kesteraernoudt** [comment]
great, thanks!

**Pull request merged**
