### PR TITLE
add proscenic integration

### PR DESCRIPTION
**Pull request by deblockt**

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @deblockt, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;wheels-custom-integrations#92).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by homeassistant** [comment]
Hi @deblockt, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;wheels-custom-integrations#92).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by pvizeli** [comment]
That will currently not work because we don't have Cairo installed. A system to automated package installation is currently not implemented

**Comment by deblockt** [comment]
I have switch from drawSvg to svgWrite to avoir this issue

**Comment by deblockt** [comment]
@pvizeli any other issue with this PR?

**Comment by frenck** [comment]
LGTM @deblockt 👍

**Pull request merged**
