### PR TITLE
Install component apk dependencies

### PR DESCRIPTION
**Pull request by dgomes**
Some components require system libraries, instead of patching the Dockerfile, I propose to extend the `manifest.json`

### CODE REVIEW

**Comment by dgomes** [comment]
@ludeeus I would appreciate your review/comments after our exchange in the morning :)

**Comment by ludeeus** [comment]
This is not enough, it only applies to one of the 2 places needed in this repo.
I think this should be discussed more broadly (like in the architecture repo) before it's added to the manifest

**Comment by ludeeus** [comment]
I think we should close this until we reach a consensus in the arch discussion, what do you think @dgomes ?

**Comment by dgomes** [comment]
I think recents changes you made completely outpace this proposal 😄

**Pull request closed without merging**
