### PR TITLE
Added manifest for cover_time_based_synced

### PR DESCRIPTION
**Pull request by kotborealis**
# Proposed change

Add manifest for [cover_time_based_synced](https://github.com/kotborealis/home-assistant-custom-components-cover-time-based-synced) custom component

# Type of change

* [x] Attempting to create an integration for Lay-Z-Spa hot tubs
  * [x] I've opened up a PR for branding on Home Assistant Brands

# Additional information

* This PR fixes or closes issue: n/a
* Link to code base pull request: n/a
* Link to documentation pull request: n/a
* Link to integration documentation on our website: n/a

### CODE REVIEW

**Comment by kotborealis** [comment]
Stil waiting... 😿

**Comment by frenck** [comment]
@kotborealis Patience is key. Thanks.

**Comment by kotborealis** [comment]
Sorry to bother you, but it's been 12 days since I've submited the pull request. Is there something wrong with it? 
I'm just trying to share my custom component on HACS and it requires me to put my manifest here.

**Comment by frenck** [comment]
CI hasn't run yet and the PR isn't reviewed yet, so the answer to the question if something is wrong cannot be answered yet.

**Review by frenck — CHANGES_REQUESTED** [review]
This custom integration hard pins a requirement that is also used by a Home Assistant Core integration:

```
xknx==0.9.4
```

This will cause problems for anybody using the KNX core integration, as that is currently pinned to 0.18.8 on the current development branch. Any user installing this custom integration will immediately break their setup if they are using the KNX core component.

Recommended is to not pin a specific version, but pin a minimum version or range instead.

**Comment by frenck** [comment]
@kotborealis Friendly ping, any updates?

**Comment by farmio** [comment]
@kotborealis Hi 👋! Please be aware that the travelcalculator Module in xknx has changed slightly since 0.9.4 so I guess some adaptions have to be made in your custom component. (Or you just vendor the old module with your component and remove the dependency for xknx - which is overkill anyway for ~150 lines of math 😉)

**Comment by kotborealis** [comment]
@farmio Thank you for suggestion!

**Pull request closed without merging**
