### PR TITLE
Add PR Custom Component

### PR DESCRIPTION
**Pull request by alandtse**

### CODE REVIEW

**Comment by ludeeus** [comment]
The integration does not have any requirements to build wheels for :+1:

**Comment by alandtse** [comment]
Actually can we reopen please? I forgot to add the requirements. It should be there now.

**Review by ludeeus — APPROVED** [review]

**Review by ludeeus — CHANGES_REQUESTED** [review]
`aiohttp` is a core requirement, you should not set that in your integration

**Comment by alandtse** [comment]
Ok will fix. I guess the assumption is that we should only list items not in the core requirements.txt huh? I'll check the dev documentation to see if we need to add it.

**Review by frenck — APPROVED** [review]
Thanks, @alandtse 👍 

LGTM now ✅

**Pull request merged**
