### PR TITLE
Create saj_modbus.json

### PR DESCRIPTION
**Pull request by wimb0**

### CODE REVIEW

**Comment by wimb0** [comment]
Seems like the Lint fails, but I don't see any issues in my json file?

**Comment by frenck** [comment]
There are quotes missing in the JSON files that is in this PR.

**Comment by wimb0** [comment]
> 
> 
> There are quotes missing in the JSON files that is in this PR.

Thanks. How could I have missed that one. 3 times...

**Review by frenck — APPROVED** [review]
Thanks, @wimb0 👍

**Pull request merged**
