### PR TITLE
Added abb_powerone_pvi_sunspec.json

### PR DESCRIPTION
**Pull request by alexdelprete**
For my custom component for ABB Power-One inverters

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @alexdelprete, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;wheels-custom-integrations#432).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by alexdelprete** [comment]
> Hi @alexdelprete,
> 
> It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant/wheels-custom-integrations#432).
> 
> Once you do that we will be able to review and accept this pull request.
> 
> Thanks!

Hi, all done.

Thanks.

**Review by frenck — APPROVED** [review]
Thanks, @alexdelprete 👍

**Comment by alexdelprete** [comment]
> Thanks, @alexdelprete 👍

Thanks to you frenck.

**Pull request merged**
