### PR TITLE
Add Oura Ring integration

### PR DESCRIPTION
**Pull request by nitobuendia**
Adds a custom_component for Oura Ring sleep sensor.

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @nitobuendia, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;wheels-custom-integrations#65).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by nitobuendia** [comment]
Signed CLA.

**Comment by nitobuendia** [comment]
Error seems unrelated to my integration:

```
parse error: Expected string key before ':' at line 1, column 4
Unable to read the manifest file at https://raw.githubusercontent.com/hasl-sensor/integration/master/custom_components/hasl/manifest.json
The URL might be wrong or is not a raw URL.
```

**Comment by frenck** [comment]
It is unrelated indeed, will go take a look at that right away.

As for your addition, your custom integration doesn't seem to have any requirements:

`"requirements": []`

As a result, there is no wheel for us the build, so adding it to this index will have no effect or benefit for anybody.

Nevertheless, thanks for contributing! 👍

**Comment by nitobuendia** [comment]
Thanks for the explanation. This seemed to be a requirement for submitting the brands logos.

**Comment by frenck** [comment]
No, it isn't a requirement, merely a hint that we also have this repository.

**Pull request closed without merging**
