### PR TITLE
feat: add awscrt

### PR DESCRIPTION
**Pull request by dahlb**
feat: add awscrt for aws iot library used by ha_hatch

### CODE REVIEW

**Review by niemyjski — APPROVED** [review]

**Comment by niemyjski** [comment]
@frenck @pvizeli would it please be possible to review this.

**Comment by rowysock** [comment]
@frenck @pvizeli We are having the same problem as @dahlb in another integration https://github.com/rowysock/home-assistant-HomeWhiz

It would help us a lot to have this PR merged. 
Thank you!

**Comment by pvizeli** [comment]
is that tested and working with our builder system? that awscrt seems to have a very hacky setup script

**Comment by GSzabados** [comment]
@MTrab, it seems to be not your Landroid integration is the only one which is having issues with awsiotsdk.

**Comment by frenck** [comment]
Because there hasn't been any activity on this PR for quite some time now, I've decided to close it for being stale.

Feel free to re-open this PR when you are ready to pick up work on it again 👍

../Frenck

**Pull request closed without merging**
