### PR TITLE
Create ha_pyamdgpuinfo.json

### PR DESCRIPTION
**Pull request by DeadEnded**

### CODE REVIEW

**Comment by DeadEnded** [comment]
Missing requirement `cython`.
Hmmm... Not sure how to proceed.

**Review by frenck — COMMENTED** [review]
I am not sure if there is any use for this? As the installation types, these wheels apply too, can't use this anyway? (Please, correct me if I'm wrong)

**Comment by DeadEnded** [comment]
First off, thanks for taking a look at this, and for being part of this amazing community!

I could be wrong - but in my testing it seems to work... I am new to all this though so I could have something wrong.  In my environment I installed the missing requirements and then was able to install `pyamdgpuinfo`.  After installing it I pulled out the wheel `pyamdgpuinfo-2.1.1-cp39-cp39-linux_x86_64.whl`.   I then recreated the container to start fresh and was able to just install the wheel I created without the requirements.

Once installed, my custom component is working... but perhaps there is something I missed?  I stopped working on this a few months ago when I found out the package wasn't available in a wheel HA could use and recently started working on it again when I found out that HA hosts wheels in `wheels-custom-integrations` for those that are not available.

What installation types are these wheels for?  My installation is the **Home Assistant Container** - do these wheels apply to this or are they for a specific installation type (**HAOS** for example).

For a quick explanation of what I am using this for:
My server has an iGPU that is being utilized by Frigate.  This component is similar to the System Monitor in that it gives sensors for GPU statistics like GPU load, temperature, memory use, etc.

Please let me know if I have misunderstood the purpose for this repo.
Thanks!
DeadEnd

**Comment by frenck** [comment]
Alright! Thanks for your extended response, lets more on! ❤️

**Review by frenck — APPROVED** [review]

**Pull request merged**
