### PR TITLE
Add Arris DCX960 component

### PR DESCRIPTION
**Pull request by Sholofly**

### CODE REVIEW

**Review by ludeeus — APPROVED** [review]
Thanks :+1:

**Comment by Sholofly** [comment]
@ludeeus Something went wrong with this PR.  The manifest file contains the wrong info. Can we revert this so I can add a new one?

**Comment by ludeeus** [comment]
No need, just make a PR that replaces the info

**Comment by Sholofly** [comment]
Yeah realized that. Sorry for any inconvenience. See #492!

**Pull request merged**
