### PR TITLE
Initial upload

### PR DESCRIPTION
**Pull request by viktak**
Hi,
I created a new custom component which I would like to share.
This is my first component for HACS and my first PR - I hope I did it the right way...
Thanks

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @viktak, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;wheels-custom-integrations#351).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by viktak** [comment]
I think I have corrected the error - I don't know how to rerun the checks...

**Comment by frenck** [comment]
Triggered re-run.

**Comment by viktak** [comment]
@frenck Can you please tell me what I am doing wrong?

The error says: `Error: components/openweathermap_all does not end with '.json'`

The file is there though:
[https://github.com/viktak/wheels-custom-integrations/blob/master/components/openweathermap_all.json](https://github.com/viktak/wheels-custom-integrations/blob/master/components/openweathermap_all.json)

Sorry about the basic question - this is my first time trying to contribute to HA.

**Comment by frenck** [comment]
You've created a subfolder. Move your file into the main folder.

`components/openweathermap_all/custom_integration.json` -> 'components/openweathermap_all.json`

**Comment by viktak** [comment]
@frenck Thank you, I finally manged to pass all the tests.

Do I have to close this?

**Pull request merged**
