### PR TITLE
Add aiortc

### PR DESCRIPTION
**Pull request by TECH7Fox**
Adds [aiortc](https://github.com/aiortc/aiortc) for the [sip client integration](https://github.com/TECH7Fox/sipclient-hass-integration) I am working on. Currently testing it on a debian HA container, but for public testing and eventually a release I need this to install `aiortc` on HA-OS.

Can't easily test this myself, can the workflow get approved please? Will update if there are any issues. :)

### CODE REVIEW

**Comment by TECH7Fox** [comment]
Seems like libsrtp was needed as well. Added it now.

**Comment by TECH7Fox** [comment]
Just added libssl-dev for pylibrtsp. aiortc and av build succesfully so it should be good now. 🤞

**Comment by TECH7Fox** [comment]
Can the CI be approved again? This should be the last, I hope.

**Comment by TECH7Fox** [comment]
It builds successfully now. This PR is ready for a review :)

**Comment by TECH7Fox** [comment]
Any ETA on when this can get a review and possibly merged?

**Review by agners — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
