### PR TITLE
add omnik inverter integration

### PR DESCRIPTION
**Pull request by klaasnicolaas**
Add Omnik Inverter integration
https://github.com/robbinjanssen/home-assistant-omnik-inverter

**Note**
Current manifest URL does not contain any dependencies yet, today there will be a
stable release that will also change this (see dev branch).

### CODE REVIEW

**Comment by frenck** [comment]
> Current manifest URL does not contain any dependencies yet

In that case, there is nothing to create wheels for and thus will fail.

**Comment by klaasnicolaas** [comment]
stable is released so we can re-run the checks 😄

**Comment by frenck** [comment]
Re-triggered run

**Review by frenck — APPROVED** [review]
Thanks, @klaasnicolaas 👍

**Pull request merged**
